--********************ORACLE DATABASE********************

CREATE TABLE RESPONSABLES (
    ID_RESPONSABLE NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    CONTACTO NUMBER,
    VETERINARIA_ID NUMBER -- Referencia lógica sin FK
);

INSERT INTO RESPONSABLES (NOMBRE, CONTACTO, VETERINARIA_ID) VALUES ('Dr. Carlos López', 5511122233, 1);
INSERT INTO RESPONSABLES (NOMBRE, CONTACTO, VETERINARIA_ID) VALUES ('Dra. Ana Torres', 5522233344, 2);
SELECT * FROM RESPONSABLES;

COMMIT;

/* FALTÓ IMPLEMENTACIÓN-->
CREATE SEQUENCE SEQ_RESPONSABLES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_RESPONSABLES_BI
BEFORE INSERT ON RESPONSABLES
FOR EACH ROW
BEGIN
    IF :NEW.ID_RESPONSABLE IS NULL THEN
        SELECT SEQ_RESPONSABLES.NEXTVAL INTO :NEW.ID_RESPONSABLE FROM DUAL;
    END IF;
END;
/

*/
