--********************ORACLE DATABASE********************

CREATE TABLE RESPONSABLES (
    ID_RESPONSABLE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    CONTACTO NUMBER,
    VETERINARIA_ID NUMBER
);

INSERT INTO RESPONSABLES (NOMBRE, CONTACTO, VETERINARIA_ID) VALUES ('Dr. Carlos López', 5511122233, 1);
INSERT INTO RESPONSABLES (NOMBRE, CONTACTO, VETERINARIA_ID) VALUES ('Dra. Ana Torres', 5522233344, 2);
SELECT * FROM RESPONSABLES;

COMMIT;